### ISSUE TITLE
Appreciation Post From Your TA 🔥- Andi Alifsyah

### ISSUE THREAD

**Issue by AndiAlifs** [naputami/Fullstack-TodoApp#1]
Hi There Kak Nadia...
I am very impressed by your project. You have done an excellent job in meeting all the requirements, 

- [x] The app functional requirements
- [x] Documenation of Code
- [x] Documentation of Repo
- [x] Presenting your demo. 

You have demonstrated great skills and creativity in developing this application. Congratulations on completing this project with magnificent results. I appreciate the documentation in your repo and code, as well as the UI that you designed (using React, which is impressive at this stage). I also enjoyed how you presented the project, from the brief, background, design, and the demo.

Congratulations on your achievement! 👏👏👏

**Comment by naputami** [comment]
Hello Kak Andi. Thank you for your appreciation. It means a lot for me. Hopefully, with the experiences i gained from this project, i can create better apps in the future. 😊
